export const FORM = {
  ru: {
    cm: 'см',
    tooSmall: 'cлишком малое значение',
    tooLarge: 'cлишком большое значение',
    required: 'обязательное поле',
    wrongInput: 'неверное значение',
    lettersRequired: 'некорректный ввод',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Адрес',
    phone: 'Телефон',
    deliveryServices: ['Нова пошта', 'УкрПошта'],
    deliveryService: 'Служба доставки',
    paymentMethod: 'Способ оплаты',
    paymentMethods: ['Оплата через менеджера', 'Оплата онлайн'],
  },
  en: {
    cm: 'cm',
    tooSmall: 'too small value',
    tooLarge: 'too large value',
    required: 'required',
    wrongInput: 'wrong input',
    lettersRequired: 'letters required',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'adress',
    phone: 'phone',
    deliveryService: 'Delivery service',
    deliveryServices: ['Нова пошта', 'УкрПошта'],
    paymentMethod: 'Payment method',
    paymentMethods: ['Payment with manager', 'Online payment'],
  },
};
