export const LANGUAGES: {
  [key: string]: {
    name: string;
    path: string;
  };
} = {
  ru: {
    name: 'укр',
    path: '',
  },
  en: {
    name: 'eng',
    path: '/en',
  },
};

export const TRANSLATE = {
  ru: {
    discountCode: 'Промокод',
    underOrder: 'Інформація про виготовлення виробу на замовлення',
    sizeUnderOrder: '(під замовлення)',
    store: 'Магазин',
    aboutUs: 'Про нас',
    cart: 'Кошик',
    search: 'Пошук',
    successOrder: 'Дякую за замовлення',
    failedOrder: 'Упс, щось пішло не так',
    tailoring: 'Індивідуальне пошиття',
    growth: 'Зріст',
    bustVolume: 'Обсяг грудей',
    waistVolume: 'Обсяг талії',
    hipsVolume: 'Обсяг стегон',
    addToCart: 'В кошик',
    backToCollection: 'Назад до колекції',
    cm: 'см',
    cartTitle: 'Ваш кошик',
    emptyCartTitle: 'поки що порожнiй.',
    continueBrowsing: ['Продовжуйте пошук', 'тут'],
    price: 'Ціна',
    total: 'В сумі',
    remove: 'Прибрати',
    goodsCaterories: 'Категорії товарів',
    outOfStock: 'Немає в наявності',
    subTotal: 'До оплати',
    agreement: 'Погодитися',
    checkOut: 'Замовити',
    checkOutAlert: 'Ви повинні погодитися з умовами, щоб оформити замовлення.',
    shipping: 'Доставка',
    continue: 'Продовжити',
    saveInfo: 'Зберегти цю інформацію',
    returnToCart: 'Повернутися до кошика',
    showOrderSummary: 'Показати деталі замовлення',
    hideOrderSummary: 'Приховати деталі замовлення',
    sizeTable: 'Таблиця розмірів',
    deliveryInfo: 'Інформація про доставку',
    returnAndExchange: 'Повернення та обмін',
    contacts: 'Контакти',
    giftCertificates: 'Подарункові сертифікати',
    giftCertificateTitle: 'Подарунковий сертифікат',
    giftCertificateDescription:
      'Цей подарунковий сертифікат буде надіслано одержувачу по E-Mail після оплати замовлення.',
    giftCertificateCartAbout: "Сертифікат на ім'я ",
    pressInformationPage: 'Інформаційна сторінка для преси',
    requestCallBackTitle:
      "Залиште заявку і менеджер зв'яжеться з Вами найближчим часом",
    requestCallBack: 'Залишити',
    copyright: 'Copyright © Blind-Blind 2021 Усі права захищені',
    privacyPolicy: 'Політика конфіденційності',
    publicContract: 'Публічний договір',
    celebrities: 'Сelebrities',
    notFoundTitle: '404 Сторінка не знайдена',
    notFoundDescription: 'Запитана вами сторінка не існує.',
    continueShopping: ['Натисніть', 'тут', 'щоб продовжити покупки.'],
    thanksForOrderTitle: 'Дякую за ваше замовлення',
    goodsNotFound: ['Ваш пошук', 'не дав жодних результатів.'],
    modalWindowStartText: 'Підписуйтесь та отримуйте унікальні пропозиції',
    subscribe: 'Підписатися',
  },
  en: {
    discountCode: 'Promocode',
    underOrder: 'Information on the manufacture of a product to order',
    sizeUnderOrder: '(under the order)',
    store: 'Store',
    aboutUs: 'About',
    cart: 'Cart',
    search: 'Search',
    successOrder: 'Thank you for your order',
    failedOrder: 'Oops, something went wrong',
    tailoring: 'Individual tailoring',
    growth: 'Growth',
    bustVolume: 'Bust',
    waistVolume: 'Waist',
    hipsVolume: 'Hips',
    addToCart: 'Add to cart',
    backToCollection: 'Back to collection',
    cm: 'cm',
    cartTitle: 'Your shopping cart',
    emptyCartTitle: 'is currently empty.',
    continueBrowsing: ['Continue browsing', 'here'],
    price: 'Price',
    total: 'Total',
    remove: 'Remove',
    goodsCaterories: "Good's categories",
    subTotal: 'Subtotal',
    agreement: 'Agree',
    checkOut: 'Check out',
    outOfStock: 'Out of stock',
    checkOutAlert:
      'You must agree with the terms and conditions of sales to check out.',
    shipping: 'Shipping',
    continue: 'Continue',
    saveInfo: 'Save this information',
    returnToCart: 'Return to cart',
    showOrderSummary: 'Show order summary',
    hideOrderSummary: 'Hide order summary',
    sizeTable: 'Size table',
    deliveryInfo: 'Delivery information',
    returnAndExchange: 'Return and exchange',
    contacts: 'Сontacts',
    giftCertificates: 'Gift certificates',
    giftCertificateTitle: 'Gift certificate',
    giftCertificateDescription:
      'This gift certificate will be sent to the recipient by E-Mail after the order has been paid.',
    giftCertificateCartAbout: 'Certificate for ',
    pressInformationPage: 'Press information page',
    requestCallBackTitle:
      'Leave a request and the manager will contact you shortly',
    requestCallBack: 'Request',
    copyright: 'Copyright © Blind-Blind 2021 All rights reserved',
    privacyPolicy: 'Privacy policy',
    publicContract: 'Public contract',
    celebrities: 'Сelebrities',
    notFoundTitle: '404 Page not found',
    notFoundDescription: 'The page you requested does not exist.',
    continueShopping: ['Click', 'here', 'to continue shopping.'],
    thanksForOrderTitle: 'Thank you for your order.',
    goodsNotFound: ['Your search for', 'did not yield any results.'],
    modalWindowStartText: 'Subscribe and receive unique offers',
    subscribe: 'Subscribe',
  },
};
