export const LANGUAGES: {
  [key: string]: {
    name: string;
    path: string;
  };
} = {
  ru: {
    name: 'рус',
    path: '',
  },
  en: {
    name: 'eng',
    path: '/en',
  },
};

export const TRANSLATE = {
  ru: {
    discountCode: 'Промокод',
    underOrder: 'Информация об изготовлении изделия под заказ',
    sizeUnderOrder: '(под заказ)',
    store: 'Магазин',
    aboutUs: 'О нас',
    cart: 'Корзина',
    search: 'Поиск',
    successOrder: 'Спасибо за заказ',
    failedOrder: 'Упс, что-то пошло не так',
    tailoring: 'Индивидульный пошив',
    growth: 'Рост',
    bustVolume: 'Объем груди',
    waistVolume: 'Объем талии',
    hipsVolume: 'Объем бедер',
    addToCart: 'В корзину',
    backToCollection: 'Назад к коллекции',
    cm: 'см',
    cartTitle: 'Ваша корзина',
    emptyCartTitle: 'пока еще пустая.',
    continueBrowsing: ['Продолжите поиск', 'здесь'],
    price: 'Цена',
    total: 'В сумме',
    remove: 'Убрать',
    goodsCaterories: 'Категории товаров',
    outOfStock: 'Нет в наличии',
    subTotal: 'К оплате',
    agreement: 'Согласиться',
    checkOut: 'Заказать',
    checkOutAlert: 'Вы должны согласиться с условиями, чтобы оформить заказ.',
    shipping: 'Доставка',
    continue: 'Продолжить',
    saveInfo: 'Сохранить эту информацию',
    returnToCart: 'Вернуться к корзине',
    showOrderSummary: 'Показать детали заказа',
    hideOrderSummary: 'Скрыть детали заказа',
    sizeTable: 'Таблица размеров',
    deliveryInfo: 'Информация о доставке',
    returnAndExchange: 'Возврат и обмен',
    contacts: 'Контакты',
    giftCertificates: 'Подарочные сертификаты',
    giftCertificateTitle: 'Подарочный сертификат',
    giftCertificateDescription:
      'Этот подарочный сертификат будет отправлен получателю по E-Mail после оплаты заказа.',
    giftCertificateCartAbout: 'Сертификат на имя ',
    pressInformationPage: 'Информационная страница для прессы',
    requestCallBackTitle:
      'Оставьте заявку и менеджер свяжется с Вами в ближайшее время',
    requestCallBack: 'Оставить',
    copyright: 'Copyright © Blind-Blind 2021 Все права защищены',
    privacyPolicy: 'Политика конфиденциальности',
    publicContract: 'Публичный договор',
    celebrities: 'Сelebrities',
    notFoundTitle: '404 Страница не найдена',
    notFoundDescription: 'Запрошенная вами страница не существует.',
    continueShopping: ['Нажите', 'здесь', 'чтобы продолжить покупки.'],
    thanksForOrderTitle: 'Спасибо за ваш заказ',
    goodsNotFound: ['Ваш поиск', 'не дал никаких результатов.'],
    modalWindowStartText: 'Подписывайтесь и получайте уникальные предложения',
    subscribe: 'Подписаться',
  },
  en: {
    discountCode: 'Promocode',
    underOrder: 'Information on the manufacture of a product to order',
    sizeUnderOrder: '(under the order)',
    store: 'Store',
    aboutUs: 'About',
    cart: 'Cart',
    search: 'Search',
    successOrder: 'Thank you for your order',
    failedOrder: 'Oops, something went wrong',
    tailoring: 'Individual tailoring',
    growth: 'Growth',
    bustVolume: 'Bust',
    waistVolume: 'Waist',
    hipsVolume: 'Hips',
    addToCart: 'Add to cart',
    backToCollection: 'Back to collection',
    cm: 'cm',
    cartTitle: 'Your shopping cart',
    emptyCartTitle: 'is currently empty.',
    continueBrowsing: ['Continue browsing', 'here'],
    price: 'Price',
    total: 'Total',
    remove: 'Remove',
    goodsCaterories: "Good's categories",
    subTotal: 'Subtotal',
    agreement: 'Agree',
    checkOut: 'Check out',
    outOfStock: 'Out of stock',
    checkOutAlert:
      'You must agree with the terms and conditions of sales to check out.',
    shipping: 'Shipping',
    continue: 'Continue',
    saveInfo: 'Save this information',
    returnToCart: 'Return to cart',
    showOrderSummary: 'Show order summary',
    hideOrderSummary: 'Hide order summary',
    sizeTable: 'Size table',
    deliveryInfo: 'Delivery information',
    returnAndExchange: 'Return and exchange',
    contacts: 'Сontacts',
    giftCertificates: 'Gift certificates',
    giftCertificateTitle: 'Gift certificate',
    giftCertificateDescription:
      'This gift certificate will be sent to the recipient by E-Mail after the order has been paid.',
    giftCertificateCartAbout: 'Certificate for ',
    pressInformationPage: 'Press information page',
    requestCallBackTitle:
      'Leave a request and the manager will contact you shortly',
    requestCallBack: 'Request',
    copyright: 'Copyright © Blind-Blind 2021 All rights reserved',
    privacyPolicy: 'Privacy policy',
    publicContract: 'Public contract',
    celebrities: 'Сelebrities',
    notFoundTitle: '404 Page not found',
    notFoundDescription: 'The page you requested does not exist.',
    continueShopping: ['Click', 'here', 'to continue shopping.'],
    thanksForOrderTitle: 'Thank you for your order.',
    goodsNotFound: ['Your search for', 'did not yield any results.'],
    modalWindowStartText: 'Subscribe and receive unique offers',
    subscribe: 'Subscribe',
  },
};
